const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const srcFile = path.join(rootDir, 'personal_brand_v4.html');

let html = fs.readFileSync(srcFile, 'utf8');
const isCrlf = html.includes('\r\n');

function replaceExact(content, target, replacement) {
  const normContent = content.replace(/\r\n/g, '\n');
  const normTarget = target.replace(/\r\n/g, '\n');
  const normRepl = replacement.replace(/\r\n/g, '\n');

  if (!normContent.includes(normTarget)) {
    throw new Error('Target snippet not found:\n' + target.slice(0, 100) + '...');
  }
  const result = normContent.replace(normTarget, normRepl);
  return isCrlf ? result.replace(/\n/g, '\r\n') : result;
}

const fullHardwareCatalogCode = `      // 19 Iconic Photorealistic Flagships across 4 Luxury Categories
      const HARDWARE_CATALOG = {
        headphones: [
          {
            id: "apple-airpods-max",
            name: "AirPods Max",
            brand: "APPLE",
            brandTag: "APPLE // CUPERTINO",
            price: 549,
            weight: "384.8 g",
            freq: "20 Hz – 20 kHz",
            driver: "40mm Apple Dynamic Transducer",
            latency: "12 ms / Dual H1 SIP",
            conn: "Bluetooth 5.0, AAC, Lightning",
            battery: "20h with ANC & Spatial Audio",
            image: "assets/hardware/studio/apple-airpods-max_hero.jpg",
            video: "assets/videos_webm/Apple_AirPods_Max_Exploded_View_20260912183607.webm",
            videoMp4: "assets/videos/Apple_AirPods_Max_Exploded_View_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/Apple_AirPods_Max_Exploded_View_20260912183607.png",
            thumbJpg: "assets/video_thumbs/Apple_AirPods_Max_Exploded_View_20260912183607.jpg",
            chassisSpec: "Anodized Aluminum & Stainless Steel Canopy",
            driverSpec: "40mm Dual Neodymium Ring Magnet Motor",
            pcbSpec: "Dual Apple H1 10-Audio-Core Computational SIP",
            baseSpec: "Acoustically Engineered Knit Mesh & Memory Foam",
            frCurve: [1.2, 2.5, 3.1, 2.8, 1.9, 0.4, 0.1, -0.2, 1.4, 3.6, 2.2, -1.0, -2.5, -4.0]
          },
          {
            id: "sony-wh1000xm5",
            name: "WH-1000XM5 ANC",
            brand: "SONY",
            brandTag: "SONY // TOKYO",
            price: 399,
            weight: "250 g",
            freq: "4 Hz – 40 kHz",
            driver: "30mm Carbon Fiber Composite Dome",
            latency: "14 ms / LDAC 990kbps",
            conn: "BT 5.2, LDAC, 3.5mm, USB-PD",
            battery: "30h Playtime (Fast Charge 3m=3h)",
            image: "assets/hardware/studio/sony-wh1000xm5_hero.jpg",
            video: "assets/videos_webm/Sony_WH-1000XM5_Exploded_View_20260912183606.webm",
            videoMp4: "assets/videos/Sony_WH-1000XM5_Exploded_View_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/Sony_WH-1000XM5_Exploded_View_20260912183606.png",
            thumbJpg: "assets/video_thumbs/Sony_WH-1000XM5_Exploded_View_20260912183606.jpg",
            chassisSpec: "Stepless Slider & Soft Fit Leather Chassis",
            driverSpec: "30mm High-Rigidity Carbon Fiber Dome Transducer",
            pcbSpec: "Integrated Processor V1 + HD QN1 Dual DSP",
            baseSpec: "Acoustically Calibrated Synthetic Soft Leather",
            frCurve: [2.2, 3.6, 4.0, 3.2, 2.1, 0.7, 0.1, -0.3, 1.2, 3.8, 2.5, -0.5, -2.1, -3.5]
          },
          {
            id: "bose-qc-ultra",
            name: "QuietComfort Ultra",
            brand: "BOSE",
            brandTag: "BOSE // FRAMINGHAM",
            price: 429,
            weight: "252 g",
            freq: "10 Hz – 20 kHz",
            driver: "35mm Custom Bio-Cellulose Driver",
            latency: "15 ms / Snapdragon Sound",
            conn: "BT 5.3, aptX Adaptive, 2.5/3.5mm",
            battery: "24h (18h Immersive Audio)",
            image: "assets/hardware/studio/bose-qc-ultra_hero.jpg",
            video: "assets/videos_webm/Bose_QuietComfort_Ultra_Exploded_View_20260912183606.webm",
            videoMp4: "assets/videos/Bose_QuietComfort_Ultra_Exploded_View_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/Bose_QuietComfort_Ultra_Exploded_View_20260912183606.png",
            thumbJpg: "assets/video_thumbs/Bose_QuietComfort_Ultra_Exploded_View_20260912183606.jpg",
            chassisSpec: "Ultra-lightweight Ergonomic Cast Aluminum Yoke",
            driverSpec: "Custom Bio-Cellulose Transient Acoustic Diaphragm",
            pcbSpec: "Qualcomm S5 Gen 2 Sound Platform with Custom Bose DSP",
            baseSpec: "Protein Leather Pillow Cushions with Active Acoustic Seal",
            frCurve: [3.1, 3.9, 3.5, 2.4, 1.2, 0.0, -0.2, 0.5, 2.1, 3.4, 1.8, -0.8, -1.9, -3.2]
          },
          {
            id: "sennheiser-hd660s2",
            name: "HD 660S2 Audiophile",
            brand: "SENNHEISER",
            brandTag: "SENNHEISER // WEDEMARK",
            price: 599,
            weight: "260 g",
            freq: "8 Hz – 41.5 kHz",
            driver: "38mm High-Performance Dynamic Transducer",
            latency: "0 ms / Balanced 4.4mm Pentaconn",
            conn: "6.35mm, 4.4mm Balanced, 3.5mm Adapter",
            battery: "Passive Audiophile Open-Back Reference",
            image: "assets/hardware/studio/sennheiser-hd660s2_hero.jpg",
            video: "assets/videos_webm/Sennheiser_HD_660S2_Exploded_View_20260912183606.webm",
            videoMp4: "assets/videos/Sennheiser_HD_660S2_Exploded_View_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/Sennheiser_HD_660S2_Exploded_View_20260912183606.png",
            thumbJpg: "assets/video_thumbs/Sennheiser_HD_660S2_Exploded_View_20260912183606.jpg",
            chassisSpec: "Acoustically Transparent Steel Mesh Open-Back Grille",
            driverSpec: "38mm Transducer with Ultra-Light Aluminum Voice Coil",
            pcbSpec: "Oxygen-Free Copper Para-Aramid Reinforced Cabling",
            baseSpec: "Plush Velour Ear Cushions for Fatigue-Free Mastering",
            frCurve: [0.5, 1.2, 1.5, 1.2, 0.8, 0.1, 0.0, 0.2, 1.1, 2.2, 1.5, 0.2, -0.8, -1.5]
          },
          {
            id: "bo-h95",
            name: "Beoplay H95",
            brand: "BANG & OLUFSEN",
            brandTag: "B&O // STRUER",
            price: 999,
            weight: "323 g",
            freq: "20 Hz – 22 kHz",
            driver: "40mm Electro-Dynamic Titanium Driver",
            latency: "14 ms / aptX Adaptive Low Latency",
            conn: "BT 5.1, aptX Adaptive, AAC, 3.5mm",
            battery: "38h with ANC Active (50h ANC Off)",
            image: "assets/hardware/studio/bo-h95_hero.jpg",
            video: "assets/videos_webm/Headphones_exploded_view_animation_20260912183607.webm",
            videoMp4: "assets/videos/Headphones_exploded_view_animation_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/Headphones_exploded_view_animation_20260912183607.png",
            thumbJpg: "assets/video_thumbs/Headphones_exploded_view_animation_20260912183607.jpg",
            chassisSpec: "Brushed Aluminum Frame with Lambskin Memory Foam",
            driverSpec: "40mm Customized Titanium Driver with Neodymium Magnets",
            pcbSpec: "Digital Signal Processing ANC with Precision Rotary Dials",
            baseSpec: "Detachable Magnetic Lambskin Ear Cushions",
            frCurve: [2.0, 2.8, 2.6, 1.8, 0.9, 0.2, 0.0, 0.4, 1.8, 2.9, 1.6, -0.4, -1.5, -2.8]
          }
        ],
        mice: [
          {
            id: "logitech-gpro-x",
            name: "G Pro X Superlight 2",
            brand: "LOGITECH G",
            brandTag: "LOGITECH // LAUSANNE",
            price: 159,
            weight: "60 g",
            freq: "2,000 Hz Polling Rate / 44,000 DPI",
            driver: "HERO 2 Optical Sensor (500+ IPS)",
            latency: "0.5 ms LIGHTSPEED Wireless",
            conn: "2.4GHz LIGHTSPEED, USB Type-C",
            battery: "95h Continuous Motion",
            image: "assets/hardware/studio/logitech-gpro-x_hero.jpg",
            video: "assets/videos_webm/Logitech_G_Pro_X_Superlight_20260912183605.webm",
            videoMp4: "assets/videos/Logitech_G_Pro_X_Superlight_20260912183605.mp4",
            thumb: "assets/video_thumbs_webm/Logitech_G_Pro_X_Superlight_20260912183605.png",
            thumbJpg: "assets/video_thumbs/Logitech_G_Pro_X_Superlight_20260912183605.jpg",
            chassisSpec: "Ultra-Thin 1mm Injection Molded Lightweight Skeleton",
            driverSpec: "LIGHTFORCE Hybrid Optical-Mechanical Switches",
            pcbSpec: "HERO 2 Next-Gen Sub-Micron Precision Tracking Sensor",
            baseSpec: "Zero-Additive Pure PTFE Low-Friction Glide Skates",
            frCurve: [0.0, 0.0, 0.0, 0.1, 0.1, 0.2, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.2]
          },
          {
            id: "razer-deathadder-v3",
            name: "DeathAdder V3 Pro",
            brand: "RAZER",
            brandTag: "RAZER // IRVINE",
            price: 169,
            weight: "63 g",
            freq: "8,000 Hz HyperPolling / 30,000 DPI",
            driver: "Focus Pro 30K Optical Sensor",
            latency: "0.125 ms HyperSpeed Wireless",
            conn: "Razer HyperSpeed Wireless, USB-C",
            battery: "90h Battery Life",
            image: "assets/hardware/studio/razer-deathadder-v3_hero.jpg",
            video: "assets/videos_webm/Razer_DeathAdder_V3_Pro_Exploded_20260912183606.webm",
            videoMp4: "assets/videos/Razer_DeathAdder_V3_Pro_Exploded_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/Razer_DeathAdder_V3_Pro_Exploded_20260912183606.png",
            thumbJpg: "assets/video_thumbs/Razer_DeathAdder_V3_Pro_Exploded_20260912183606.jpg",
            chassisSpec: "Iconic Ergonomic Split-Key Palm Support Architecture",
            driverSpec: "Optical Mouse Switches Gen-3 Rated for 90M Clicks",
            pcbSpec: "Focus Pro 30K Sensor with 99.8% Resolution Accuracy",
            baseSpec: "Flawless Contoured 100% PTFE Smooth Edge Skates",
            frCurve: [0.0, 0.1, 0.1, 0.1, 0.2, 0.2, 0.3, 0.4, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5]
          },
          {
            id: "apple-magic-mouse-2",
            name: "Magic Mouse Multi-Touch",
            brand: "APPLE",
            brandTag: "APPLE // CUPERTINO",
            price: 79,
            weight: "99 g",
            freq: "Multi-Touch Gesture Recognition Engine",
            driver: "Capacitive Sub-Surface Gesture Array",
            latency: "8 ms Bluetooth Optimized",
            conn: "Bluetooth, Lightning Charging",
            battery: "About a Month per Charge",
            image: "assets/hardware/studio/apple-magic-mouse-2_hero.jpg",
            video: "assets/videos_webm/Apple_Magic_Mouse_2_Exploded_20260912183605.webm",
            videoMp4: "assets/videos/Apple_Magic_Mouse_2_Exploded_20260912183605.mp4",
            thumb: "assets/video_thumbs_webm/Apple_Magic_Mouse_2_Exploded_20260912183605.png",
            thumbJpg: "assets/video_thumbs/Apple_Magic_Mouse_2_Exploded_20260912183605.jpg",
            chassisSpec: "Continuous Seamless Top Shell Multi-Touch Surface",
            driverSpec: "Capacitive Sensor Array with Micro-Switch Tactile Mechanism",
            pcbSpec: "Custom Apple ARM Controller for Gesture Coordinate Processing",
            baseSpec: "Optimized High-Density Polyethylene Low-Resistance Rails",
            frCurve: [0.0, 0.0, 0.1, 0.1, 0.1, 0.2, 0.2, 0.3, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
          },
          {
            id: "zowie-ec2-cw",
            name: "EC2-CW Esports Wireless",
            brand: "BENQ ZOWIE",
            brandTag: "ZOWIE // TAIPEI",
            price: 149,
            weight: "77 g",
            freq: "1,000 Hz Polling Rate / 3370 Sensor",
            driver: "PixArt 3370 Optical Sensor",
            latency: "1.0 ms Enhanced Wireless Receiver",
            conn: "2.4G Wireless Enhanced Stand, USB-C",
            battery: "70h Competitive Playtime",
            image: "assets/hardware/studio/zowie-ec2-cw_hero.jpg",
            video: "assets/videos_webm/ZOWIE_EC2-CW_Exploded_View_20260912183606.webm",
            videoMp4: "assets/videos/ZOWIE_EC2-CW_Exploded_View_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/ZOWIE_EC2-CW_Exploded_View_20260912183606.png",
            thumbJpg: "assets/video_thumbs/ZOWIE_EC2-CW_Exploded_View_20260912183606.jpg",
            chassisSpec: "Asymmetrical Ergonomic Shell Engineered for Palm/Claw Grip",
            driverSpec: "Huano Blue Shell Pink Dot Switches with 24-Step Optical Wheel",
            pcbSpec: "Interference-Resistant Enhanced Directional Wireless Antenna",
            baseSpec: "Large Surface Area High-Durability Black Teflon Skates",
            frCurve: [0.0, 0.1, 0.1, 0.2, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0, 1.2, 1.4]
          },
          {
            id: "logitech-mx-master-3s",
            name: "MX Master 3S Ergonomic",
            brand: "LOGITECH",
            brandTag: "LOGITECH // LAUSANNE",
            price: 99,
            weight: "141 g",
            freq: "8,000 DPI Darkfield High-Precision",
            driver: "Darkfield Any-Surface Glass Tracking",
            latency: "4 ms Logi Bolt / Bluetooth Low Energy",
            conn: "Logi Bolt Receiver, Bluetooth, USB-C",
            battery: "70 Days Full Charge (3h on 1 min)",
            image: "assets/hardware/studio/logitech-mx-master-3s_hero.jpg",
            video: "assets/videos_webm/Mouse_disassembly_product_visual_20260912183605.webm",
            videoMp4: "assets/videos/Mouse_disassembly_product_visual_20260912183605.mp4",
            thumb: "assets/video_thumbs_webm/Mouse_disassembly_product_visual_20260912183605.png",
            thumbJpg: "assets/video_thumbs/Mouse_disassembly_product_visual_20260912183605.jpg",
            chassisSpec: "Sculpted Hand-Crafted Ergonomic Chassis with Thumb Rest",
            driverSpec: "MagSpeed Electromagnetic Stainless Steel SmartScroll Wheel",
            pcbSpec: "8K Darkfield Optical Sensor with Quiet Click Dampeners",
            baseSpec: "Four High-Grade PTFE Gliding Pads for Silent Glide",
            frCurve: [0.0, 0.0, 0.1, 0.1, 0.2, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
          }
        ],
        speakers: [
          {
            id: "sonos-era-300",
            name: "Era 300 Spatial Audio",
            brand: "SONOS",
            brandTag: "SONOS // SANTA BARBARA",
            price: 449,
            weight: "4.47 kg",
            freq: "Dolby Atmos Spatial Acoustic Waveguide",
            driver: "6 Class-D Digital Amplifiers + 4 Tweeters + 2 Woofers",
            latency: "Wi-Fi 6 Synchronized Multi-Room Audio",
            conn: "Wi-Fi 6, Bluetooth 5.0, USB-C Line-In, AirPlay 2",
            battery: "AC Power (Continuous Studio Playback)",
            image: "assets/hardware/studio/sonos-era-300_hero.jpg",
            video: "assets/videos_webm/Sonos_Era_300_Exploded_View_20260912183607.webm",
            videoMp4: "assets/videos/Sonos_Era_300_Exploded_View_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/Sonos_Era_300_Exploded_View_20260912183607.png",
            thumbJpg: "assets/video_thumbs/Sonos_Era_300_Exploded_View_20260912183607.jpg",
            chassisSpec: "Hourglass Acoustic Compression Chamber with Precision Grille",
            driverSpec: "Six Precision-Calibrated Drivers Optimized for Dolby Atmos",
            pcbSpec: "Trueplay Tuning Quad-Core A55 Neural Audio DSP",
            baseSpec: "Vibration-Isolating Silicone Damping Footpad",
            frCurve: [2.5, 3.8, 4.2, 3.5, 2.0, 0.8, 0.2, -0.1, 1.5, 3.2, 2.0, -0.6, -1.8, -3.0]
          },
          {
            id: "marshall-stanmore-3",
            name: "Stanmore III Bluetooth",
            brand: "MARSHALL",
            brandTag: "MARSHALL // LONDON",
            price: 379,
            weight: "4.25 kg",
            freq: "45 Hz – 20,000 Hz",
            driver: "50 Watt Class D Woofer + 2x 15 Watt Class D Tweeters",
            latency: "aptX Low Latency Audio",
            conn: "Bluetooth 5.2 (LE Audio ready), 3.5mm AUX, RCA",
            battery: "Mains Powered 100-240V",
            image: "assets/hardware/studio/marshall-stanmore-3_hero.jpg",
            video: "assets/videos_webm/Marshall_Stanmore_III_Exploded_View_20260912183607.webm",
            videoMp4: "assets/videos/Marshall_Stanmore_III_Exploded_View_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/Marshall_Stanmore_III_Exploded_View_20260912183607.png",
            thumbJpg: "assets/video_thumbs/Marshall_Stanmore_III_Exploded_View_20260912183607.jpg",
            chassisSpec: "Vintage Textured Vinyl with Brass Accents and Wooden Cabinet",
            driverSpec: "Outward-Angled Tweeters and Updated Waveguides for Wide Soundstage",
            pcbSpec: "Dynamic Loudness DSP Adjusting Tonal Balance Across Volumes",
            baseSpec: "Non-Slip Rubber Acoustic Isolation Feet",
            frCurve: [3.5, 4.5, 4.0, 2.8, 1.5, 0.3, -0.2, 0.2, 1.8, 2.8, 1.5, -0.5, -1.5, -2.5]
          },
          {
            id: "jbl-flip-6",
            name: "Flip 6 Waterproof Portable",
            brand: "JBL",
            brandTag: "HARMAN // STAMFORD",
            price: 129,
            weight: "550 g",
            freq: "63 Hz – 20,000 Hz",
            driver: "2-Way Speaker System (Racetrack Woofer + Separate Tweeter)",
            latency: "Low-Latency Bluetooth 5.1",
            conn: "Bluetooth 5.1, JBL PartyBoost",
            battery: "12 Hours Playtime (2.5h Charge Time)",
            image: "assets/hardware/studio/jbl-flip-6_hero.jpg",
            video: "assets/videos_webm/JBL_Flip_6_Exploded_View_20260912183607.webm",
            videoMp4: "assets/videos/JBL_Flip_6_Exploded_View_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/JBL_Flip_6_Exploded_View_20260912183607.png",
            thumbJpg: "assets/video_thumbs/JBL_Flip_6_Exploded_View_20260912183607.jpg",
            chassisSpec: "IP67 Waterproof & Dustproof Rugged Fabric Housing",
            driverSpec: "Racetrack-Shaped Woofer with Dual Passive Radiators",
            pcbSpec: "Harman DSP Optimization with USB-C Charging Protection",
            baseSpec: "Integrated Silicone Grip Rails and Impact-Resistant Endcaps",
            frCurve: [2.0, 3.2, 3.0, 2.0, 1.0, 0.1, -0.3, 0.4, 2.0, 3.0, 1.2, -1.0, -2.0, -3.2]
          },
          {
            id: "bose-revolve-2",
            name: "SoundLink Revolve+ II",
            brand: "BOSE",
            brandTag: "BOSE // FRAMINGHAM",
            price: 329,
            weight: "900 g",
            freq: "True 360-Degree Omnidirectional Sound",
            driver: "Downward-Firing Full-Range Transducer + Omnidirectional Deflector",
            latency: "Low Latency Wireless Sync",
            conn: "Bluetooth 4.2, 3.5mm AUX, Micro-B USB",
            battery: "17 Hours per Charge",
            image: "assets/hardware/studio/bose-revolve-2_hero.jpg",
            video: "assets/videos_webm/Bose_SoundLink_Revolve_II_Exploded_20260912183607.webm",
            videoMp4: "assets/videos/Bose_SoundLink_Revolve_II_Exploded_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/Bose_SoundLink_Revolve_II_Exploded_20260912183607.png",
            thumbJpg: "assets/video_thumbs/Bose_SoundLink_Revolve_II_Exploded_20260912183607.jpg",
            chassisSpec: "Seamless Anodized Aluminum Cylindrical Body (IP55 Water Resistant)",
            driverSpec: "Dual Opposing Passive Radiators & Omnidirectional Acoustic Deflector",
            pcbSpec: "Stereo / Party Mode Pairing Engine with Voice Prompt DSP",
            baseSpec: "Soft Impact-Absorbing Molded Bumpers and Threaded Mount Base",
            frCurve: [1.8, 2.8, 2.5, 1.6, 0.8, 0.0, -0.2, 0.3, 1.6, 2.5, 1.0, -0.8, -1.6, -2.5]
          },
          {
            id: "devialet-phantom-i",
            name: "Phantom I 108dB",
            brand: "DEVIALET",
            brandTag: "DEVIALET // PARIS",
            price: 3199,
            weight: "11.4 kg",
            freq: "14 Hz – 27,000 Hz",
            driver: "1100 Watts RMS / Grade 1 Titanium Tweeter",
            latency: "0 ms Devialet Wireless Link",
            conn: "Wi-Fi, AirPlay 2, Bluetooth, Optical TOSLink",
            battery: "Mains Powered (1100W Peak Transient Power)",
            image: "assets/hardware/studio/devialet-phantom-i_hero.jpg",
            video: "assets/videos_webm/Speaker_exploded-view_product_vi_20260912183606.webm",
            videoMp4: "assets/videos/Speaker_exploded-view_product_vi_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/Speaker_exploded-view_product_vi_20260912183606.png",
            thumbJpg: "assets/video_thumbs/Speaker_exploded-view_product_vi_20260912183606.jpg",
            chassisSpec: "Composite Body with 22-Carat Rose Gold Gilded Sides",
            driverSpec: "Hermetically Sealed Dual Push-Push Woofers with SAM Emulation",
            pcbSpec: "ADH Next-Gen Hybrid Analog-Digital Amplification Core",
            baseSpec: "Ultra-Rigid Damped Cast Aluminum Foundation",
            frCurve: [4.8, 5.2, 4.5, 3.2, 1.8, 0.4, 0.0, 0.6, 2.2, 3.8, 2.2, -0.2, -1.0, -1.8]
          }
        ],
        keyboards: [
          {
            id: "keychron-q1-pro",
            name: "Q1 Pro QMK/VIA Wireless",
            brand: "KEYCHRON",
            brandTag: "KEYCHRON // KOWLOON",
            price: 199,
            weight: "1.73 kg",
            freq: "1,000 Hz Polling Rate (Wired)",
            driver: "Double-Gasket CNC Aluminum Chassis",
            latency: "1.0 ms Wired / 8 ms BT 5.1",
            conn: "Bluetooth 5.1, USB Type-C Detachable",
            battery: "4000mAh Battery (300h RGB Off)",
            image: "assets/hardware/studio/keychron-q1-pro_hero.jpg",
            video: "assets/videos_webm/Keychron_Q1_Pro_Exploded_View_20260912183607.webm",
            videoMp4: "assets/videos/Keychron_Q1_Pro_Exploded_View_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/Keychron_Q1_Pro_Exploded_View_20260912183607.png",
            thumbJpg: "assets/video_thumbs/Keychron_Q1_Pro_Exploded_View_20260912183607.jpg",
            chassisSpec: "Full 6063 CNC Machined Aluminum Double-Gasket Mount",
            driverSpec: "Hot-Swappable K Pro Banana Switches with Screw-in PCB Stabs",
            pcbSpec: "Ultra-Low-Power ARM Cortex-M4 32-bit STM32L432 (128KB Flash)",
            baseSpec: "Sound Absorbing Acoustic Foam & Case Silicone Dampening Pad",
            frCurve: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.0, 0.8, 0.6, 0.4, 0.2, 0.0, 0.0]
          },
          {
            id: "logitech-g915-tkl",
            name: "G915 TKL LIGHTSPEED",
            brand: "LOGITECH G",
            brandTag: "LOGITECH // LAUSANNE",
            price: 229,
            weight: "810 g",
            freq: "1,000 Hz Polling Rate / 1.5mm Actuation",
            driver: "Low Profile GL Tactile Mechanical Switches",
            latency: "1.0 ms Pro-Grade LIGHTSPEED",
            conn: "LIGHTSPEED Wireless, Bluetooth, Micro-USB",
            battery: "40 Hours at 100% RGB Brightness",
            image: "assets/hardware/studio/logitech-g915-tkl_hero.jpg",
            video: "assets/videos_webm/Logitech_G915_TKL_Exploded_View_20260912183606.webm",
            videoMp4: "assets/videos/Logitech_G915_TKL_Exploded_View_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/Logitech_G915_TKL_Exploded_View_20260912183606.png",
            thumbJpg: "assets/video_thumbs/Logitech_G915_TKL_Exploded_View_20260912183606.jpg",
            chassisSpec: "Aircraft-Grade 5052 Aluminum-Magnesium Alloy Top Case",
            driverSpec: "High-Performance Low-Profile GL Mechanical Switches (50g Force)",
            pcbSpec: "LIGHTSPEED Wireless Sub-Millisecond Report Frequency Module",
            baseSpec: "Ultra-Slim 22mm Profile with Dual Rubberized Tilt Feet",
            frCurve: [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.0, 0.8, 0.6, 0.5, 0.3, 0.2, 0.1, 0.0]
          },
          {
            id: "apple-magic-keyboard",
            name: "Magic Keyboard with Touch ID",
            brand: "APPLE",
            brandTag: "APPLE // CUPERTINO",
            price: 179,
            weight: "243 g",
            freq: "Secure Enclave Touch ID Biometric Engine",
            driver: "Refined Scissor Mechanism (1mm Travel)",
            latency: "8 ms Bluetooth Low Energy",
            conn: "Bluetooth, Lightning, Wireless",
            battery: "Internal Battery (Over 1 Month per Charge)",
            image: "assets/hardware/studio/apple-magic-keyboard_hero.jpg",
            video: "assets/videos_webm/Apple_Magic_Keyboard_Exploded_View_20260912183607.webm",
            videoMp4: "assets/videos/Apple_Magic_Keyboard_Exploded_View_20260912183607.mp4",
            thumb: "assets/video_thumbs_webm/Apple_Magic_Keyboard_Exploded_View_20260912183607.png",
            thumbJpg: "assets/video_thumbs/Apple_Magic_Keyboard_Exploded_View_20260912183607.jpg",
            chassisSpec: "Precision 100% Recycled Aluminum Unibody Enclosure",
            driverSpec: "Ultra-Low Profile Scissor Mechanism with Optimized Key Stability",
            pcbSpec: "Secure Enclave Hardware Biometric Authentication SIP",
            baseSpec: "Four Recessed High-Tack Non-Slip Rubber Base Footpads",
            frCurve: [0.0, 0.1, 0.2, 0.3, 0.5, 0.7, 0.8, 0.7, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
          },
          {
            id: "razer-huntsman-v3",
            name: "Huntsman V3 Pro TKL",
            brand: "RAZER",
            brandTag: "RAZER // IRVINE",
            price: 219,
            weight: "880 g",
            freq: "1,000 Hz / Adjustable Actuation 0.1 – 4.0mm",
            driver: "Gen-2 Analog Optical Switches with Rapid Trigger",
            latency: "0.2 ms Analog Optical Detection",
            conn: "Detachable Braided Type-C Cable",
            battery: "Wired Tournament-Grade Zero-Drop Connection",
            image: "assets/hardware/studio/razer-huntsman-v3_hero.jpg",
            video: "assets/videos_webm/Razer_Huntsman_V3_Pro_Exploded_20260912183606.webm",
            videoMp4: "assets/videos/Razer_Huntsman_V3_Pro_Exploded_20260912183606.mp4",
            thumb: "assets/video_thumbs_webm/Razer_Huntsman_V3_Pro_Exploded_20260912183606.png",
            thumbJpg: "assets/video_thumbs/Razer_Huntsman_V3_Pro_Exploded_20260912183606.jpg",
            chassisSpec: "5052 Brushed Aluminum Top Plate with Magnetic Leatherette Wrist Rest",
            driverSpec: "Analog Optical Switches with Rapid Trigger & Stepless Actuation",
            pcbSpec: "Multi-Function Digital Dial & Dedicated Macro Tactical Buttons",
            baseSpec: "Textured Double-Shot PBT Keycaps Resistant to Wear & Shine",
            frCurve: [0.5, 0.8, 1.0, 0.7, 0.3, 0.0, 0.1, 0.5, 1.0, 1.2, 0.8, 0.1, -0.3, -0.5]
          }
        ]
      };`;

const catMatch = html.match(/(\s*\/\/\s*19 Iconic Photorealistic Flagships[\s\S]*?const HARDWARE_CATALOG = \{[\s\S]*?\n\s*\};)/);
if (!catMatch) {
  throw new Error('Could not find existing HARDWARE_CATALOG in personal_brand_v4.html');
}

html = replaceExact(html, catMatch[1], fullHardwareCatalogCode);
fs.writeFileSync(srcFile, html);
console.log('Successfully updated HARDWARE_CATALOG in personal_brand_v4.html');
